### ISSUE TITLE
Is llap restricted to a special version of llvm?

### ISSUE THREAD

**Issue by flynightair** [michaelbrownuc/llap#1]
Hi, michaelbrownuc. Is the llap restricted to a special version of llvm? 
For example, the 10.0.0 llvm in the vulchecker

**Comment by michaelbrownuc** [comment]
not necessarily, but currently that is the supported version. It can be updated to a newer version of LLVM in a fairly straightforward manner, but I'm not actively supporting llap.  Happy to take a PR if you want to update it!

**Comment by flynightair** [comment]
> not necessarily, but currently that is the supported version. It can be updated to a newer version of LLVM in a fairly straightforward manner, but I'm not actively supporting llap. Happy to take a PR if you want to update it!

Thanks for your reply. I'm trying to apply the llap to llvm 15.0.4, hoping for the success
